---
# tasks file for sshd-role
- name: sshd template
  template: 
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    validate: '/usr/sbin/sshd -t -f %s'
  notify: 'restart sshd'
- name: sshd restart
  systemd:
    name: sshd 
    state: restarted
